Update devpi
wbrp/docker-devpi pull request #2
Opened 2022-09-28 15:42 UTC by nbro10

Hopefully, solves https://github.com/wbrp/deploy-devpi/issues/4

Do we need [this file](https://github.com/wbrp/docker-devpi/blob/update-devpi/devpi/upgrade.sh)? If not, I can delete it and update the `Dockerfile` not to copy it into the container.

Note: 

1. This PR removes an image (`data`), which I think was unnecessary because it just used to create a folder, but we can do it in the `devpi` image
2. This PR changes the base images from `alpine:3.4` to `python:3.8.14-slim` because I was getting an error installing `devpi-server` on that image. I think we could solve this problem by installing more dependencies, like [here](https://github.com/dmartin35/docker-devpi/blob/master/Dockerfile#L11), but, after having done that, it seemed like the image was larger than `python:3.8.14-slim`, but I could be wrong because I haven't investigated this much

2022-09-28 16:00 UTC, ddoskind commented
@nbro10 I think the `upgrade.sh` file is indeed no longer used as devpi now seems to have the ability to upgrade in-place. Feel free to add a commit removing it.

2022-09-28 16:09 UTC, nbro10 commented
@ddoskind So, probably, we also don't need the folder `/devpi/server-upgrade` inside the container, right? I am not sure. This folder is mapped to a volume and it may contain some files already.

2022-09-28 16:29 UTC, ddoskind commented
> @ddoskind So, probably, we also don't need the folder `/devpi/server-upgrade` inside the container, right? I am not sure. This folder is mapped to a volume and it may contain some files already.

I am almost certain this is correct, yes.

2022-09-29 17:31 UTC, nbro10 commented
@ddoskind I removed the `/devpi/server-upgrade` folder inside the container and the corresponding volume. Let me know if I should change something else. 

Btw, idk if you noticed, but I changed the `docker-compose.yml` to use [named volumes](https://github.com/wbrp/docker-devpi/blob/update-devpi/docker-compose.yml#L18), while, previously, we were using anonymous volumes. I wonder how the saved anonymous volume is used instead of the named one. `ls /var/lib/docker/volumes` inside `deploy-devpi` does not show the named volumes but `docker volume ls` does.

2022-09-30 04:55 UTC, ddoskind commented
ACK until next week 👍

2022-10-04 15:11 UTC, ddoskind requested changes
Perfectly fine, but please slim down the `.gitignore` file a bit and remove the reference to the `server-upgrade` volume from the docs 👍

2022-10-04 15:11 UTC, ddoskind commented on .gitignore
> +# MacOS .gitignore
This is very comprehensive, that's why I'd recommend using it as a global .gitignore file and only add those entries in project repositories which you expect to be relevant (e.g. a `VENV` directory when there's makefiles that create one, etc.)

2022-10-04 15:11 UTC, ddoskind commented on README.md
> +`server-upgrade`.
This should be adjusted as `server-upgrade` is no longer required.

2022-10-11 09:39 UTC, ddoskind approved these changes
🌈  Merge away

2022-10-11 09:52 UTC, merged